<svg
  data-v-4f22e642=""
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  width="100%"
  height="100%"
  class=""
>
  <defs data-v-4f22e642="">
    <pattern
      id="pattern"
      width="50"
      height="50"
      viewBox="0 0 40 40"
      patternUnits="userSpaceOnUse"
      patternTransform="rotate(45)"
    >
      <rect
        id="pattern-background"
        x="0"
        y="0"
        width="400%"
        height="400%"
        fill="#2d3748"
      ></rect>
      <circle
        cx="34"
        cy="20"
        r="4"
        fill="#4a5568"
        stroke="#4a5568"
        stroke-width="0"
      ></circle>
      <circle
        cx="6"
        cy="20"
        r="4"
        fill="#4a5568"
        stroke="#4a5568"
        stroke-width="0"
      ></circle>
      <circle
        cx="20"
        cy="34"
        r="4"
        fill="#4a5568"
        stroke="#4a5568"
        stroke-width="0"
      ></circle>
      <circle
        cx="20"
        cy="6"
        r="4"
        fill="#4a5568"
        stroke="#4a5568"
        stroke-width="0"
      ></circle>
      <circle
        cx="34"
        cy="6"
        r="4"
        fill="#1a202c"
        stroke="#1a202c"
        stroke-width="0"
      ></circle>
      <circle
        cx="6"
        cy="34"
        r="4"
        fill="#1a202c"
        stroke="#1a202c"
        stroke-width="0"
      ></circle>
      <circle
        cx="34"
        cy="34"
        r="4"
        fill="#1a202c"
        stroke="#1a202c"
        stroke-width="0"
      ></circle>
      <circle
        cx="6"
        cy="6"
        r="4"
        fill="#1a202c"
        stroke="#1a202c"
        stroke-width="0"
      ></circle>
    </pattern>
  </defs>
  <rect
    data-v-4f22e642=""
    fill="url(#pattern)"
    height="100%"
    width="100%"
    y="0"
    x="0"
  ></rect>
</svg>
