const defaultTheme = require('tailwindcss/defaultTheme')
const tinycolor = require('tinycolor2')
// const plugin = require('tailwindcss/plugin')

module.exports = {
  // whitelist
  // corePlugins: [],
  // or disable individually
  corePlugins: {
    float: false,
    objectFit: false,
    objectPosition: false,
  },
  theme: {
    fontFamily: {
      sans: ['Inter', '"Source Sans Pro"', ...defaultTheme.fontFamily.sans],
      serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'JetBrains Mono',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    aspectRatio: {
      square: [1, 1],
      '16/9': [16, 9],
      '4/3': [4, 3],
      '21/9': [21, 9],
    },
    extend: {
      screens: {
        '2xl': '1440px',
        dark: { raw: '(prefers-color-scheme: dark)' },
        light: { raw: '(prefers-color-scheme: light)' },
      },
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        tertiary: 'var(--color-tertiary)',
        danger: 'var(--color-danger)',
        facebook: 'var(--color-facebook)',
        copy: 'var(--color-copy)',
        emailer: 'var(--color-emailer)',
        sms: 'var(--color-sms)',
        text: 'var(--color-text)',
        'booster-blue': '#003E7E', // hsla(210, 100%, 25%, 1)
        'booster-red': '#B3282D', // hsla(358, 63%, 43%, 1)
        // primary: 'var(--color-primary)',
        'primary-darkest': '#118d36',
        'primary-darker': '#1c9d48',
        'primary-dark': '#28ae5c',
        // primary: '#2db564',
        'primary-base': '#2db564',
        'primary-light': '#6ccb93',
        'primary-lighter': '#96dab2',
        'primary-lightest': '#c0e9d1',
        'primary-25': tinycolor('#2f855a').setAlpha(0.25).toRgbString(),
        'primary-50': tinycolor('#2f855a').setAlpha(0.5).toRgbString(),
        'primary-75': tinycolor('#2f855a').setAlpha(0.75).toRgbString(),
        // primary: {
        //   100: '#EAF8F0',
        //   200: '#CBEDD8',
        //   300: '#ABE1C1',
        //   400: '#6CCB93',
        //   500: '#2DB564',
        //   600: '#29A35A',
        //   700: '#1B6D3C',
        //   800: '#14512D',
        //   900: '#0E361E',
        // },
        // secondary: 'var(--color-secondary)',
        'secondary-darkest': '#1256c8',
        'secondary-darker': '#1d69d1',
        'secondary-dark': '#297eda',
        // secondary: '#2e86de',
        'secondary-base': '#2e86de',
        'secondary-light': '#4d98e3',
        'secondary-lighter': '#97c3ef',
        'secondary-lightest': '#c0dbf5',
        'secondary-25': tinycolor('#2b6cb0').setAlpha(0.25).toRgbString(),
        'secondary-50': tinycolor('#2b6cb0').setAlpha(0.5).toRgbString(),
        'secondary-75': tinycolor('#2b6cb0').setAlpha(0.75).toRgbString(),
        // secondary: {
        //   100: '#EAF3FC',
        //   200: '#CBE1F7',
        //   300: '#ABCFF2',
        //   400: '#6DAAE8',
        //   500: '#2E86DE',
        //   600: '#2979C8',
        //   700: '#1C5085',
        //   800: '#153C64',
        //   900: '#0E2843',
        // },
        // tertiary: 'var(--color-tertiary)',
        'tertiary-darkest': '#ff5625',
        'tertiary-darker': '#ff733d',
        'tertiary-dark': '#ff7e46',
        // tertiary: '#ff864d',
        'tertiary-base': '#ff864d',
        'tertiary-light': '#ff9868',
        'tertiary-lighter': '#ffaa82',
        'tertiary-lightest': '#ffdbca',
        'tertiary-25': tinycolor('#ed8936').setAlpha(0.25).toRgbString(),
        'tertiary-50': tinycolor('#ed8936').setAlpha(0.5).toRgbString(),
        'tertiary-75': tinycolor('#ed8936').setAlpha(0.75).toRgbString(),
        // tertiary: {
        //   100: '#FFF6EB',
        //   200: '#FEE9CD',
        //   300: '#FDDBAF',
        //   400: '#FCC174',
        //   500: '#FAA638',
        //   600: '#E19532',
        //   700: '#966422',
        //   800: '#714B19',
        //   900: '#4B3211',
        // },
        // danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        success: 'var(--color-success)',
        info: 'var(--color-info)',
        easyemailer: 'var(--color-easyemailer)',
        message: 'var(--color-message)',
        brand: '#1B2A60',
        // facebook: '#3b5998',
        twitter: '#1da1f2',
        linkedin: '#0077b5',
        'grey-darkest': '#3d4852',
        'grey-darker': '#606f7b',
        'grey-dark': '#8795a1',
        grey: '#b8c2cc',
        'grey-base': '#b8c2cc',
        'grey-light': '#dae1e7',
        'grey-lighter': '#f1f5f8',
        'grey-lightest': '#f8fafc',
        red: '#e3342f',
        orange: '#f6993f',
        yellow: '#ffed4a',
        green: '#38c172',
        teal: '#4dc0b5',
        blue: '#3490dc',
        indigo: '#6574cd',
        purple: '#9561e2',
        pink: '#f66d9b',
      },
      boxShadow: {
        outline: '0 0 0 3px rgba(66, 153, 225, 0.25)',
        huge: '0 30px 60px -15px rgba(0, 0, 0, .25)',
        'outline-red': '0 0 0 3px rgba(249, 89, 89, 0.15)',
        'outline-green': '0 0 0 3px rgba(5,202,160, 0.8)',
        'solid-white': '0 0 0 2px #fff',
      },
      height: {
        '1/4': '25%',
      },
      spacing: {
        '2px': '2px',
        7: '1.75rem',
        9: '2.25rem',
        11: '2.75rem',
        13: '3.25rem',
        14: '3.5rem',
        15: '3.75rem',
        28: '7rem',
        44: '11rem',
        72: '18rem',
        80: '20rem',
        84: '21rem',
        96: '24rem',
        108: '27rem',
        128: '32rem',
        160: '40rem',
      },
      inset: {
        '-16': '-4rem',
      },
      fontSize: {
        '2xs': '0.625rem',
      },
      textColor: {
        // primary: 'var(--color-text-primary)',
        // secondary: 'var(--color-text-secondary)',
        default: 'var(--color-text-default)',
        'default-soft': 'var(--color-text-default-soft)',
        inverse: 'var(--color-text-inverse)',
        'inverse-soft': 'var(--color-text-inverse-soft)',
      },
    },
  },
  variants: {
    backgroundColor: ['responsive', 'group-hover', 'hover', 'focus', 'active'],
    borderColor: ['responsive', 'group-hover', 'hover', 'focus'],
    display: ['responsive', 'group-hover'],
    textColor: ['responsive', 'group-hover', 'hover', 'focus-within', 'focus', 'active'],
    zIndex: ['responsive', 'focus-within', 'focus'],
  },
  plugins: [
    require('@tailwindcss/ui'),
    require('tailwindcss-aspect-ratio'),
    require('tailwindcss-elevation')(['responsive']),
    require('tailwindcss-scrims')({
      directions: {
        t: 'to bottom',
        b: 'to top',
        r: 'to left',
        l: 'to right',
      },
      distances: {
        '1/4': '25%',
        '1/3': '33.33333%',
        '1/2': '50%',
        '2/3': '66.66666%',
        '3/4': '75%',
      },
      colors: {
        default: ['rgba(0, 0, 0, 0.4)', 'rgba(0, 0, 0, 0)'],
      },
      variants: ['responsive', 'hover'],
    }),
    function ({ addBase, config }) {
      addBase({
        h1: { fontSize: config('theme.fontSize.2xl') },
        h2: { fontSize: config('theme.fontSize.xl') },
        h3: { fontSize: config('theme.fontSize.lg') },
      })
    },
    function ({ addComponents }) {
      const buttons = {
        // '.btn': {
        //   padding: '.5rem 1rem',
        //   borderRadius: '.25rem',
        //   fontWeight: '600',
        // },
        '.btn-blue': {
          backgroundColor: '#3490dc',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#2779bd',
          },
        },
        '.btn-red': {
          backgroundColor: '#e3342f',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#cc1f1a',
          },
        },
      }

      addComponents(buttons)
    },
  ],
}
