<?php

use Illuminate\Database\Seeder;
use App\Entities\GradeAlias;

class GradeAliasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        GradeAlias::insert([
            ['grade_id' => '-2', 'alias' => '-2'],
            ['grade_id' => '-2', 'alias' => 'autism'],
            ['grade_id' => '-2', 'alias' => 'autistic'],
            ['grade_id' => '-2', 'alias' => 'ee'],
            ['grade_id' => '-2', 'alias' => 'intermedia'],
            ['grade_id' => '-2', 'alias' => 'intermediate'],
            ['grade_id' => '-2', 'alias' => 'pre-1'],
            ['grade_id' => '-2', 'alias' => 'pre-1st'],
            ['grade_id' => '-2', 'alias' => 'pre1'],
            ['grade_id' => '-2', 'alias' => 'pre1st'],
            ['grade_id' => '-2', 'alias' => 'readiness'],
            ['grade_id' => '-2', 'alias' => 'ready'],
            ['grade_id' => '-2', 'alias' => 'specialed'],
            ['grade_id' => '-2', 'alias' => 'specialneeds'],
            ['grade_id' => '-2', 'alias' => 'specnd'],
            ['grade_id' => '-2', 'alias' => 'specneeds'],
            ['grade_id' => '-1', 'alias' => '-1'],
            ['grade_id' => '-1', 'alias' => '02k'],
            ['grade_id' => '-1', 'alias' => '02p'],
            ['grade_id' => '-1', 'alias' => '02pk'],
            ['grade_id' => '-1', 'alias' => '03k'],
            ['grade_id' => '-1', 'alias' => '03p'],
            ['grade_id' => '-1', 'alias' => '03pk'],
            ['grade_id' => '-1', 'alias' => '2p'],
            ['grade_id' => '-1', 'alias' => '2pk'],
            ['grade_id' => '-1', 'alias' => '3-pk'],
            ['grade_id' => '-1', 'alias' => '3p'],
            ['grade_id' => '-1', 'alias' => '3pk'],
            ['grade_id' => '-1', 'alias' => '4-k'],
            ['grade_id' => '-1', 'alias' => '4-pk'],
            ['grade_id' => '-1', 'alias' => '4k'],
            ['grade_id' => '-1', 'alias' => 'p'],
            ['grade_id' => '-1', 'alias' => 'p2'],
            ['grade_id' => '-1', 'alias' => 'p2k'],
            ['grade_id' => '-1', 'alias' => 'p3'],
            ['grade_id' => '-1', 'alias' => 'p3-2'],
            ['grade_id' => '-1', 'alias' => 'p32'],
            ['grade_id' => '-1', 'alias' => 'p3k'],
            ['grade_id' => '-1', 'alias' => 'P4'],
            ['grade_id' => '-1', 'alias' => 'p4-5'],
            ['grade_id' => '-1', 'alias' => 'p4-k'],
            ['grade_id' => '-1', 'alias' => 'p41'],
            ['grade_id' => '-1', 'alias' => 'p42'],
            ['grade_id' => '-1', 'alias' => 'p43'],
            ['grade_id' => '-1', 'alias' => 'p44'],
            ['grade_id' => '-1', 'alias' => 'p45'],
            ['grade_id' => '-1', 'alias' => 'p4k'],
            ['grade_id' => '-1', 'alias' => 'p4kk'],
            ['grade_id' => '-1', 'alias' => 'p5'],
            ['grade_id' => '-1', 'alias' => 'p5k'],
            ['grade_id' => '-1', 'alias' => 'pf2'],
            ['grade_id' => '-1', 'alias' => 'pf3'],
            ['grade_id' => '-1', 'alias' => 'pf4'],
            ['grade_id' => '-1', 'alias' => 'pk'],
            ['grade_id' => '-1', 'alias' => 'pk-3'],
            ['grade_id' => '-1', 'alias' => 'pk-4'],
            ['grade_id' => '-1', 'alias' => 'pk2'],
            ['grade_id' => '-1', 'alias' => 'pk3'],
            ['grade_id' => '-1', 'alias' => 'pk3-k'],
            ['grade_id' => '-1', 'alias' => 'pk3k'],
            ['grade_id' => '-1', 'alias' => 'pk4'],
            ['grade_id' => '-1', 'alias' => 'pk4-5'],
            ['grade_id' => '-1', 'alias' => 'pk45'],
            ['grade_id' => '-1', 'alias' => 'pre-k'],
            ['grade_id' => '-1', 'alias' => 'pre-kindergarten'],
            ['grade_id' => '-1', 'alias' => 'prek'],
            ['grade_id' => '-1', 'alias' => 'prekindergarten'],
            ['grade_id' => '-1', 'alias' => 'tk'],
            ['grade_id' => '0' , 'alias' => '0'],
            ['grade_id' => '0' , 'alias' => '0k'],
            ['grade_id' => '0' , 'alias' => '5-k'],
            ['grade_id' => '0' , 'alias' => '5k'],
            ['grade_id' => '0' , 'alias' => 'k'],
            ['grade_id' => '0' , 'alias' => 'k-4'],
            ['grade_id' => '0' , 'alias' => 'k-5'],
            ['grade_id' => '0' , 'alias' => 'k4'],
            ['grade_id' => '0' , 'alias' => 'k4a'],
            ['grade_id' => '0' , 'alias' => 'k4b'],
            ['grade_id' => '0' , 'alias' => 'k4c'],
            ['grade_id' => '0' , 'alias' => 'k4d'],
            ['grade_id' => '0' , 'alias' => 'k4e'],
            ['grade_id' => '0' , 'alias' => 'k5'],
            ['grade_id' => '0' , 'alias' => 'k5a'],
            ['grade_id' => '0' , 'alias' => 'k5b'],
            ['grade_id' => '0' , 'alias' => 'k5c'],
            ['grade_id' => '0' , 'alias' => 'k5d'],
            ['grade_id' => '0' , 'alias' => 'k5e'],
            ['grade_id' => '0' , 'alias' => 'kg'],
            ['grade_id' => '0' , 'alias' => 'kg-4'],
            ['grade_id' => '0' , 'alias' => 'kg-5'],
            ['grade_id' => '0' , 'alias' => 'ki'],
            ['grade_id' => '0' , 'alias' => 'kinder'],
            ['grade_id' => '0' , 'alias' => 'kindergarten'],
            ['grade_id' => '0' , 'alias' => 'kk'],
            ['grade_id' => '0' , 'alias' => 'kk-4'],
            ['grade_id' => '0' , 'alias' => 'kk-5'],
            ['grade_id' => '0' , 'alias' => 'kk4'],
            ['grade_id' => '0' , 'alias' => 'kk5'],
            ['grade_id' => '0' , 'alias' => 'kl'],
            ['grade_id' => '0' , 'alias' => 'kn'],
            ['grade_id' => '0' , 'alias' => 'ku'],
            ['grade_id' => '0' , 'alias' => 'primary'],
            ['grade_id' => '1' , 'alias' => '1'],
            ['grade_id' => '1' , 'alias' => '1 st'],
            ['grade_id' => '1' , 'alias' => '1a'],
            ['grade_id' => '1' , 'alias' => '1b'],
            ['grade_id' => '1' , 'alias' => '1c'],
            ['grade_id' => '1' , 'alias' => '1d'],
            ['grade_id' => '1' , 'alias' => '1st'],
            ['grade_id' => '1' , 'alias' => 'first'],
            ['grade_id' => '1' , 'alias' => 'first grade'],
            ['grade_id' => '1' , 'alias' => 'firstgrade'],
            ['grade_id' => '2' , 'alias' => '2'],
            ['grade_id' => '2' , 'alias' => '2 nd'],
            ['grade_id' => '2' , 'alias' => '2a'],
            ['grade_id' => '2' , 'alias' => '2b'],
            ['grade_id' => '2' , 'alias' => '2c'],
            ['grade_id' => '2' , 'alias' => '2d'],
            ['grade_id' => '2' , 'alias' => '2nd'],
            ['grade_id' => '2' , 'alias' => 'second'],
            ['grade_id' => '2' , 'alias' => 'second grade'],
            ['grade_id' => '2' , 'alias' => 'secondgrade'],
            ['grade_id' => '3' , 'alias' => '3'],
            ['grade_id' => '3' , 'alias' => '3 rd'],
            ['grade_id' => '3' , 'alias' => '3a'],
            ['grade_id' => '3' , 'alias' => '3b'],
            ['grade_id' => '3' , 'alias' => '3c'],
            ['grade_id' => '3' , 'alias' => '3d'],
            ['grade_id' => '3' , 'alias' => '3rd'],
            ['grade_id' => '3' , 'alias' => 'third'],
            ['grade_id' => '3' , 'alias' => 'third grade'],
            ['grade_id' => '3' , 'alias' => 'thirdgrade'],
            ['grade_id' => '4' , 'alias' => '4'],
            ['grade_id' => '4' , 'alias' => '4 th'],
            ['grade_id' => '4' , 'alias' => '4a'],
            ['grade_id' => '4' , 'alias' => '4b'],
            ['grade_id' => '4' , 'alias' => '4c'],
            ['grade_id' => '4' , 'alias' => '4d'],
            ['grade_id' => '4' , 'alias' => '4th'],
            ['grade_id' => '4' , 'alias' => 'fourth'],
            ['grade_id' => '4' , 'alias' => 'fourth grade'],
            ['grade_id' => '4' , 'alias' => 'fourthgrade'],
            ['grade_id' => '5' , 'alias' => '5'],
            ['grade_id' => '5' , 'alias' => '5 th'],
            ['grade_id' => '5' , 'alias' => '5a'],
            ['grade_id' => '5' , 'alias' => '5b'],
            ['grade_id' => '5' , 'alias' => '5c'],
            ['grade_id' => '5' , 'alias' => '5d'],
            ['grade_id' => '5' , 'alias' => '5th'],
            ['grade_id' => '5' , 'alias' => 'fifth'],
            ['grade_id' => '5' , 'alias' => 'fifth grade'],
            ['grade_id' => '5' , 'alias' => 'fifthgrade'],
            ['grade_id' => '6' , 'alias' => '6'],
            ['grade_id' => '6' , 'alias' => '6 th'],
            ['grade_id' => '6' , 'alias' => '6a'],
            ['grade_id' => '6' , 'alias' => '6b'],
            ['grade_id' => '6' , 'alias' => '6c'],
            ['grade_id' => '6' , 'alias' => '6d'],
            ['grade_id' => '6' , 'alias' => '6th'],
            ['grade_id' => '6' , 'alias' => 'sixth'],
            ['grade_id' => '6' , 'alias' => 'sixth grade'],
            ['grade_id' => '6' , 'alias' => 'sixthgrade'],
            ['grade_id' => '7' , 'alias' => '7'],
            ['grade_id' => '7' , 'alias' => '7 th'],
            ['grade_id' => '7' , 'alias' => '7a'],
            ['grade_id' => '7' , 'alias' => '7b'],
            ['grade_id' => '7' , 'alias' => '7c'],
            ['grade_id' => '7' , 'alias' => '7d'],
            ['grade_id' => '7' , 'alias' => '7th'],
            ['grade_id' => '7' , 'alias' => 'seventh'],
            ['grade_id' => '7' , 'alias' => 'seventh grade'],
            ['grade_id' => '7' , 'alias' => 'seventhgrade'],
            ['grade_id' => '8' , 'alias' => '8'],
            ['grade_id' => '8' , 'alias' => '8 th'],
            ['grade_id' => '8' , 'alias' => '8a'],
            ['grade_id' => '8' , 'alias' => '8b'],
            ['grade_id' => '8' , 'alias' => '8c'],
            ['grade_id' => '8' , 'alias' => '8d'],
            ['grade_id' => '8' , 'alias' => '8th'],
            ['grade_id' => '8' , 'alias' => 'eighth'],
            ['grade_id' => '8' , 'alias' => 'eighth grade'],
            ['grade_id' => '8' , 'alias' => 'eighthgrade'],
            ['grade_id' => '9' , 'alias' => '9'],
            ['grade_id' => '9' , 'alias' => '9 th'],
            ['grade_id' => '9' , 'alias' => '9a'],
            ['grade_id' => '9' , 'alias' => '9b'],
            ['grade_id' => '9' , 'alias' => '9c'],
            ['grade_id' => '9' , 'alias' => '9d'],
            ['grade_id' => '9' , 'alias' => '9th'],
            ['grade_id' => '9' , 'alias' => 'ninth'],
            ['grade_id' => '9' , 'alias' => 'ninth grade'],
            ['grade_id' => '9' , 'alias' => 'ninthgrade'],
            ['grade_id' => '10', 'alias' => '10 th'],
            ['grade_id' => '10', 'alias' => '10th'],
            ['grade_id' => '10', 'alias' => 'tenth'],
            ['grade_id' => '10', 'alias' => 'tenth grade'],
            ['grade_id' => '11', 'alias' => '11 th'],
            ['grade_id' => '11', 'alias' => '11th'],
            ['grade_id' => '11', 'alias' => 'eleventh'],
            ['grade_id' => '11', 'alias' => 'eleventh grade'],
            ['grade_id' => '11', 'alias' => 'eleventhgrade'],
            ['grade_id' => '12', 'alias' => '12 th'],
            ['grade_id' => '12', 'alias' => '12th'],
            ['grade_id' => '12', 'alias' => 'twelth'],
            ['grade_id' => '12', 'alias' => 'twelth grade'],
            ['grade_id' => '12', 'alias' => 'twelthgrade'],
        ]);
    }
}
