<?php

use Illuminate\Database\Seeder;
use App\Entities\Program;
use App\Entities\Group;
use App\Entities\Classroom;
use Carbon\Carbon;

class ProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Giving Market Program Type
        $program_type_giving_market = DB::table('program_types')->where('namespace', 'giving_market')->first();
        $giving_market_programs     = [];

        //Carbon
        $futureWeekPast   = Carbon::now()->subDays(7);
        $futureYearFuture = Carbon::now()->addYears(1);
        $currentSemester  = date('Y') . (date('m') < 7 ? '-1-Spring' : '-2-Fall');

        //Active Non-Giving Market Program 1 Reading Unit Type
        factory(Program::class, 1)->create([
            'id'                               => 1,
            'name'                             => 'Salesforce Test-2016-2-Fall',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MA6',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzf',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123456,
            'event_name'                       => 'Salesforce /@$!%^&*() Kenny',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 2,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => null,
        ]);

        //Active Non Giving Market Program 2 Laps Unit Type
        factory(Program::class, 1)->create([
            'id'                               => 2,
            'name'                             => 'Salesforce Test Active Non Giving Market',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MAO',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFza',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123457,
            'event_name'                       => 'Salesforce Active Non Giving Market',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 1,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => null,
        ]);

        //Archived Non-Giving Market Program
        factory(Program::class, 1)->create([
            'id'                               => 3,
            'name'                             => 'Salesforce Test Archived Non-Giving Market',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => '2016-08-02 00:00:00',
            'fun_run'                          => '2016-10-30 00:00:00',
            'due_date'                         => '2016-12-31 00:00:00',
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MA1',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzb',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 1,
            'open_help'                        => 0,
            'registration_code'                => 123458,
            'event_name'                       => 'Salesforce Archived Non-Giving Market',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 2,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => null,
        ]);

        //Active Giving Market Program 1
        factory(Program::class, 1)->create([
            'id'                               => 4,
            'name'                             => 'Salesforce Test Active Giving Market 1',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MA2',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzc',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123459,
            'event_name'                       => 'Salesforce Active Giving Market 1',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 2,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => $program_type_giving_market->id,
        ]);

        //Active Giving Market Program 2
        factory(Program::class, 1)->create([
            'id'                               => 5,
            'name'                             => 'Salesforce Test Active Giving Market 2',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MA3',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzd',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123451,
            'event_name'                       => 'Salesforce Active Giving Market 2',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 2,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => $program_type_giving_market->id,
        ]);

        //Active Giving Market Program 3
        factory(Program::class, 1)->create([
            'id'                               => 6,
            'name'                             => 'Salesforce Test Active Giving Market 3',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MA4',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFze',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123452,
            'event_name'                       => 'Salesforce Active Giving Market 3',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 2,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => $program_type_giving_market->id,
        ]);

        //Active Non Giving Market Program with Flat Pledging
        factory(Program::class, 1)->create([
            'id'                               => 7,
            'name'                             => 'Salesforce Test Active Non Giving Market Flat Pledging',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MA5',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzg',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123453,
            'event_name'                       => 'Salesforce Active Non Giving Market 4',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 2,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => null,
        ]);

        //Active Non Giving Market Program with Golden Rule Unit Type
        factory(Program::class, 1)->create([
            'id'                               => 8,
            'name'                             => 'Salesforce Test Active Non Giving Market Golden Rule Unit Type',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MB2',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzh',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123454,
            'event_name'                       => 'Salesforce Active Non Giving Market Golden Rule Unit',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 4,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => null,
        ]);
        factory(Program::class, 5)->create();

        // Assign classrooms to giving market programs
        foreach ($giving_market_programs as $program_id) {
            $group = factory(Group::class)->create(
                ['program_id' => $program_id]
            );

            factory(Classroom::class)->create(['group_id' => $group->id]);
        }

        //Active Non Giving Market Program with Event - Bash Unit Type
        $program = factory(Program::class, 1)->create([
            // 'id'                               => 9,
            'name'                             => 'Salesforce Test Active Non Giving Market Event - Bash Unit Type',
            'school_id'                        => 1,
            'preprogram_students_total'        => null,
            'preprogram_homerooms'             => null,
            'projected_students'               => null,
            'projected_raised'                 => 3250,
            'projected_raised_per_student'     => null,
            'pep_rally'                        => $futureWeekPast,
            'fun_run'                          => $futureYearFuture,
            'due_date'                         => $futureYearFuture,
            'teacher_party'                    => null,
            'preprogram'                       => null,
            'preprogram_fr'                    => null,
            'parent_membership'                => null,
            'teacher_party_location'           => null,
            'preprogram_scheduled'             => null,
            'semester'                         => $currentSemester,
            'projected_revenue'                => null,
            'school_contact_group'             => null,
            'pledged'                          => null,
            'actual_students'                  => null,
            'participating_students'           => null,
            'payee'                            => '',
            'deleted'                          => 0,
            'team_id'                          => 13,
            'owner_id'                         => 54,
            'sf_opportunity_id'                => '006U000000Tg2keIAB',
            'salesforce_id'                    => 'a4MU0000001JCN3MB3',
            'salesforce_team_id'               => 'Test',
            'sf_school_id'                     => '001U000000BjAF7IAN',
            'sf_owner_id'                      => '005U0000000iXcYIAU',
            'collection_type'                  => 'donor_base',
            'pledging_start'                   => '2016-08-01 08:00:00',
            'pledging_end'                     => '2216-08-01 08:00:00',
            'collection_refer_key'             => 'XxgPQFzi',
            'sponsor_convenience_fee'          => '0.00',
            'optional_sponsor_fee'             => '2.00',
            'school_processing_fee'            => '2.00',
            'online_payment_enabled'           => 1,
            'hold_online_payments'             => null,
            'daily_pledge_target'              => 526,
            'pledge_target'                    => 3421,
            'total_raised_goal'                => 133000,
            'client_percent'                   => null,
            'client_goal'                      => 66500,
            'archived'                         => 0,
            'open_help'                        => 0,
            'registration_code'                => 123455,
            'event_name'                       => 'Salesforce Active Non Giving Market Event - Bash Unit',
            'parent_email_prompts'             => 1,
            'facebook_share_prize'             => 0,
            'restrict_access_prize_reports'    => null,
            'has_delivered_top_prizes'         => 1,
            'online_payment_required'          => 0,
            'filter_merchant_report_by_school' => null,
            'unit_id'                          => 7,
            'has_delivered_teacher_prizes'     => 1,
            'promote_pay_online'               => 0,
            'program_type_id'                  => null,
        ]);
    }
}
