<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Role::insert(
            [
                [
                'id'            => 1,
                'name'          => 'admin',
                'guard_name'    => 'web',
                'description'   => 'Locker Access',
                'salesforce_id' => null,
                'type'          => 'Internal-External',
                ],
                [
                'id'            => 2,
                'name'          => 'members',
                'guard_name'    => 'web',
                'description'   => 'General User',
                'salesforce_id' => null,
                'type'          => 'Internal-External',
                ],
                [
                'id'            => 3,
                'name'          => 'students',
                'guard_name'    => 'web',
                'description'   => 'Student/Participants',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 4,
                'name'          => 'sponsors',
                'guard_name'    => 'web',
                'description'   => 'Sponsors',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 5,
                'name'          => 'parents',
                'guard_name'    => 'web',
                'description'   => 'Parents',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 6,
                'name'          => 'Client Adminstrator',
                'guard_name'    => 'web',
                'description'   => 'Client Administrator',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 7,
                'name'          => 'teachers',
                'guard_name'    => 'web',
                'description'   => 'Teachers',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 8,
                'name'          => 'volunteers',
                'guard_name'    => 'web',
                'description'   => 'Volunteers',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 9,
                'name'          => 'editors',
                'guard_name'    => 'web',
                'description'   => 'Content Editors',
                'salesforce_id' => null,
                'type'          => 'Internal',
                ],
                [
                'id'            => 10,
                'name'          => 'developers',
                'guard_name'    => 'web',
                'description'   => 'Developers',
                'salesforce_id' => null,
                'type'          => 'Internal',
                ],
                [
                'id'            => 11,
                'name'          => 'participants',
                'guard_name'    => 'web',
                'description'   => 'Participants',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 12,
                'name'          => 'Hattiesburg',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000Gw69IAC',
                'type'          => 'team',
                ],
                [
                'id'            => 13,
                'name'          => 'Test',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000Gw64IAC',
                'type'          => 'team',
                ],
                [
                'id'            => 14,
                'name'          => 'Greenville',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtmXIAS',
                'type'          => 'team',
                ],
                [
                'id'            => 15,
                'name'          => 'Nashville',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtmcIAC',
                'type'          => 'team',
                ],
                [
                'id'            => 16,
                'name'          => 'Tampa',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHvIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 17,
                'name'          => 'Sales',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHwIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 18,
                'name'          => 'Human Resources',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtI0IAK',
                'type'          => 'team',
                ],
                [
                'id'            => 19,
                'name'          => 'Client Experience',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtI5IAK',
                'type'          => 'team',
                ],
                [
                'id'            => 20,
                'name'          => 'DC',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHHIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 21,
                'name'          => 'Charlotte',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtH2IAK',
                'type'          => 'team',
                ],
                [
                'id'            => 22,
                'name'          => 'Atlanta',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtGsIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 23,
                'name'          => 'Columbia',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtH7IAK',
                'type'          => 'team',
                ],
                [
                'id'            => 24,
                'name'          => 'Birmingham',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtGxIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 25,
                'name'          => 'Huntsville',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHRIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 26,
                'name'          => 'Raleigh',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHlIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 27,
                'name'          => 'Orlando',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHgIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 28,
                'name'          => 'Jacksonville',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHWIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 29,
                'name'          => 'South Florida',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHqIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 30,
                'name'          => 'Houston',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHMIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 31,
                'name'          => 'Finance',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtIFIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 32,
                'name'          => 'Executive',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtIKIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 33,
                'name'          => 'Dallas',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHCIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 34,
                'name'          => 'Memphis',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtHbIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 35,
                'name'          => 'Business Development',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GtIAIA0',
                'type'          => 'team',
                ],
                [
                'id'            => 36,
                'name'          => 'Tallahassee',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GuIkIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 37,
                'name'          => 'Phoenix',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GuIfIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 38,
                'name'          => 'Chicago',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000GuIaIAK',
                'type'          => 'team',
                ],
                [
                'id'            => 39,
                'name'          => 'Charleston',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000Gv6oIAC',
                'type'          => 'team',
                ],
                [
                'id'            => 40,
                'name'          => 'Denver',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000yF49IAE',
                'type'          => 'team',
                ],
                [
                'id'            => 41,
                'name'          => 'Philadelphia',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000yGmIIAU',
                'type'          => 'team',
                ],
                [
                'id'            => 42,
                'name'          => 'Open',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000yHhoIAE',
                'type'          => 'team',
                ],
                [
                'id'            => 43,
                'name'          => 'Cincinnati',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000yGmNIAU',
                'type'          => 'team',
                ],
                [
                'id'            => 44,
                'name'          => 'Elevate',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000ZjW6IAK',
                'type'          => 'team',
                ],
                [
                'id'            => 46,
                'name'          => 'Technology',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000001FDAGIA4',
                'type'          => 'team',
                ],
                [
                'id'            => 47,
                'name'          => 'Corporate',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000000sBxOIAU',
                'type'          => 'team',
                ],
                [
                'id'            => 49,
                'name'          => 'Remote Support',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000001rLJFIA2',
                'type'          => 'team',
                ],
                [
                'id'            => 50,
                'name'          => 'Organization Admin',
                'guard_name'    => 'web',
                'description'   => 'Organization Administrator',
                'salesforce_id' => null,
                'type'          => 'Internal',
                ],
                [
                'id'            => 1000,
                'name'          => 'System Administrator',
                'guard_name'    => 'web',
                'description'   => 'SysAdmin-Access Global tabs (Prizes, Users, User Groups)',
                'salesforce_id' => null,
                'type'          => 'Internal',
                ],
                [
                'id'            => 1001,
                'name'          => 'Minnesota',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000002DE4DIAW',
                'type'          => 'team',
                ],
                [
                'id'            => 1002,
                'name'          => 'Sales 2',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000002N8cWIAS',
                'type'          => 'team',
                ],
                [
                'id'            => 1003,
                'name'          => 'Operations',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000002xMriIAE',
                'type'          => 'team',
                ],
                [
                'id'            => 1004,
                'name'          => 'Home Office',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000004quNHIAY',
                'type'          => 'team',
                ],
                [
                'id'            => 1005,
                'name'          => 'Oklahoma City',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU00000058SEoIAM',
                'type'          => 'team',
                ],
                [
                'id'            => 1006,
                'name'          => 'Southern California',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU00000058SEeIAM',
                'type'          => 'team',
                ],
                [
                'id'            => 1007,
                'name'          => 'New York',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU00000059wTNIAY',
                'type'          => 'team',
                ],
                [
                'id'            => 1008,
                'name'          => 'Central Texas',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005KwrJIAS',
                'type'          => 'team',
                ],
                [
                'id'            => 1009,
                'name'          => 'Baltimore',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005KwqzIAC',
                'type'          => 'team',
                ],
                [
                'id'            => 1010,
                'name'          => 'Our of Market',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005L911IAC',
                'type'          => 'team',
                ],
                [
                'id'            => 1011,
                'name'          => 'Boston',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005LBh5IAG',
                'type'          => 'team',
                ],
                [
                'id'            => 1012,
                'name'          => 'Jackson',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005lUXzIAM',
                'type'          => 'team',
                ],
                [
                'id'            => 1013,
                'name'          => 'OM Fun Run You',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005oOUpIAM',
                'type'          => 'team',
                ],
                [
                'id'            => 1014,
                'name'          => 'National Expansion',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000005oOV9IAM',
                'type'          => 'team',
                ],
                [
                'id'            => 1015,
                'name'          => 'Little Rock',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU00000069tsNIAQ',
                'type'          => 'team',
                ],
                [
                'id'            => 1016,
                'name'          => 'National Expansion 2',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000006AZMGIA4',
                'type'          => 'team',
                ],
                [
                'id'            => 1017,
                'name'          => 'OM Express',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000006AZMBIA4',
                'type'          => 'team',
                ],
                [
                'id'            => 1018,
                'name'          => 'Logistics',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000006C5utIAC',
                'type'          => 'team',
                ],
                [
                'id'            => 1019,
                'name'          => 'Sales Demo',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000006DBxyIAG',
                'type'          => 'team',
                ],
                [
                'id'            => 1020,
                'name'          => 'Orginization Admin C',
                'guard_name'    => 'web',
                'description'   => 'Organization Administrator for Collections',
                'salesforce_id' => null,
                'type'          => 'External',
                ],
                [
                'id'            => 1021,
                'name'          => 'Northern California',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000006kr2dIAA',
                'type'          => 'team',
                ],
                [
                'id'            => 1022,
                'name'          => 'Program Consultant &',
                'guard_name'    => 'web',
                'description'   => 'Team created to house the personnel and data that is '
                    . 'involved with the execution of Boosterthon\'s re',
                'salesforce_id' => 'a1sU0000004w9UnIAI',
                'type'          => 'team',
                ],
                [
                'id'            => 1023,
                'name'          => '3BT',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1sU0000004w9QCIAY',
                'type'          => 'team',
                ],
                [
                'id'            => 1024,
                'name'          => 'Chesapeake',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FqErQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1025,
                'name'          => 'Greensboro',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FqGiQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1026,
                'name'          => 'Wilmington',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FqGnQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1027,
                'name'          => 'Richmond',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FqGsQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1028,
                'name'          => 'Milwaukee',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FqGxQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1029,
                'name'          => 'Corporate 2',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsPkQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1030,
                'name'          => 'Indianapolis',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FpqUQAS',
                'type'          => 'team',
                ],
                [
                'id'            => 1031,
                'name'          => 'Kansas City',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FpIpQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1032,
                'name'          => 'Mobile',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FqEmQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1033,
                'name'          => 'Tulsa',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsXmQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1034,
                'name'          => 'Savannah',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FpaBQAS',
                'type'          => 'team',
                ],
                [
                'id'            => 1035,
                'name'          => 'Seattle',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsZnQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1036,
                'name'          => 'Cleveland',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsZYQA0',
                'type'          => 'team',
                ],
                [
                'id'            => 1037,
                'name'          => 'Hartford',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsZiQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1038,
                'name'          => 'Colorado Springs',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsZsQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1039,
                'name'          => 'Long Island',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsZdQAK',
                'type'          => 'team',
                ],
                [
                'id'            => 1040,
                'name'          => 'Lexington',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P000007FsgRQAS',
                'type'          => 'team',
                ],
                [
                'id'            => 1041,
                'name'          => 'Knoxville',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P0000070wcqQAA',
                'type'          => 'team',
                ],
                [
                'id'            => 1042,
                'name'          => 'Marketing',
                'guard_name'    => 'web',
                'description'   => null,
                'salesforce_id' => 'a1s0P0000070xTdQAI',
                'type'          => 'team',
                ]
            ]
        );
    }
}
