<?php

use App\Entities\Country;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    private $countries = [
        ['iso' => 'US', 'name' => 'United States'],
        ['iso' => 'AF', 'name' => 'Afghanistan'],
        ['iso' => 'AL', 'name' => 'Albania'],
        ['iso' => 'DZ', 'name' => 'Algeria'],
        ['iso' => 'AS', 'name' => 'American Samoa'],
        ['iso' => 'AD', 'name' => 'Andorra'],
        ['iso' => 'AO', 'name' => 'Angola'],
        ['iso' => 'AI', 'name' => 'Anguilla'],
        ['iso' => 'AQ', 'name' => 'Antarctica'],
        ['iso' => 'AG', 'name' => 'Antigua and Barbuda'],
        ['iso' => 'AR', 'name' => 'Argentina'],
        ['iso' => 'AM', 'name' => 'Armenia'],
        ['iso' => 'AW', 'name' => 'Aruba'],
        ['iso' => 'AU', 'name' => 'Australia'],
        ['iso' => 'AT', 'name' => 'Austria'],
        ['iso' => 'AZ', 'name' => 'Azerbaijan'],
        ['iso' => 'BS', 'name' => 'Bahamas'],
        ['iso' => 'BH', 'name' => 'Bahrain'],
        ['iso' => 'BD', 'name' => 'Bangladesh'],
        ['iso' => 'BB', 'name' => 'Barbados'],
        ['iso' => 'BY', 'name' => 'Belarus'],
        ['iso' => 'BE', 'name' => 'Belgium'],
        ['iso' => 'BZ', 'name' => 'Belize'],
        ['iso' => 'BJ', 'name' => 'Benin'],
        ['iso' => 'BM', 'name' => 'Bermuda'],
        ['iso' => 'BT', 'name' => 'Bhutan'],
        ['iso' => 'BO', 'name' => 'Bolivia'],
        ['iso' => 'BA', 'name' => 'Bosnia and Herzegovina'],
        ['iso' => 'BW', 'name' => 'Botswana'],
        ['iso' => 'BR', 'name' => 'Brazil'],
        ['iso' => 'IO', 'name' => 'British Indian Ocean'],
        ['iso' => 'VG', 'name' => 'British Virgin Islands'],
        ['iso' => 'BN', 'name' => 'Brunei'],
        ['iso' => 'BG', 'name' => 'Bulgaria'],
        ['iso' => 'BF', 'name' => 'Burkina Faso'],
        ['iso' => 'MM', 'name' => 'Burma'],
        ['iso' => 'BI', 'name' => 'Burundi'],
        ['iso' => 'KH', 'name' => 'Cambodia'],
        ['iso' => 'CM', 'name' => 'Cameroon'],
        ['iso' => 'CA', 'name' => 'Canada'],
        ['iso' => 'CV', 'name' => 'Cape Verde'],
        ['iso' => 'KY', 'name' => 'Cayman Islands'],
        ['iso' => 'CF', 'name' => 'Central African Republic'],
        ['iso' => 'TD', 'name' => 'Chad'],
        ['iso' => 'CL', 'name' => 'Chile'],
        ['iso' => 'CN', 'name' => 'China'],
        ['iso' => 'CX', 'name' => 'Christmas Island'],
        ['iso' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
        ['iso' => 'CO', 'name' => 'Colombia'],
        ['iso' => 'KM', 'name' => 'Comoros'],
        ['iso' => 'CD', 'name' => 'Congo, D.R.'],
        ['iso' => 'CG', 'name' => 'Congo, Republic of the'],
        ['iso' => 'CK', 'name' => 'Cook Islands'],
        ['iso' => 'CR', 'name' => 'Costa Rica'],
        ['iso' => 'HR', 'name' => 'Croatia'],
        ['iso' => 'CU', 'name' => 'Cuba'],
        ['iso' => 'CW', 'name' => 'Curacao'],
        ['iso' => 'CY', 'name' => 'Cyprus'],
        ['iso' => 'CZ', 'name' => 'Czech Republic'],
        ['iso' => 'DK', 'name' => 'Denmark'],
        ['iso' => 'DJ', 'name' => 'Djibouti'],
        ['iso' => 'DM', 'name' => 'Dominica'],
        ['iso' => 'DO', 'name' => 'Dominican Republic'],
        ['iso' => 'TL', 'name' => 'East Timor'],
        ['iso' => 'EC', 'name' => 'Ecuador'],
        ['iso' => 'EG', 'name' => 'Egypt'],
        ['iso' => 'SV', 'name' => 'El Salvador'],
        ['iso' => 'GQ', 'name' => 'Equatorial Guinea'],
        ['iso' => 'ER', 'name' => 'Eritrea'],
        ['iso' => 'EE', 'name' => 'Estonia'],
        ['iso' => 'ET', 'name' => 'Ethiopia'],
        ['iso' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
        ['iso' => 'FO', 'name' => 'Faroe Islands'],
        ['iso' => 'FJ', 'name' => 'Fiji'],
        ['iso' => 'FI', 'name' => 'Finland'],
        ['iso' => 'FR', 'name' => 'France'],
        ['iso' => 'GF', 'name' => 'French Guiana'],
        ['iso' => 'PF', 'name' => 'French Polynesia'],
        ['iso' => 'GA', 'name' => 'Gabon'],
        ['iso' => 'GM', 'name' => 'Gambia'],
        ['iso' => 'GE', 'name' => 'Georgia'],
        ['iso' => 'DE', 'name' => 'Germany'],
        ['iso' => 'GH', 'name' => 'Ghana'],
        ['iso' => 'GI', 'name' => 'Gibraltar'],
        ['iso' => 'GR', 'name' => 'Greece'],
        ['iso' => 'GL', 'name' => 'Greenland'],
        ['iso' => 'GD', 'name' => 'Grenada'],
        ['iso' => 'GP', 'name' => 'Guadeloupe'],
        ['iso' => 'GU', 'name' => 'Guam'],
        ['iso' => 'GT', 'name' => 'Guatemala'],
        ['iso' => 'GN', 'name' => 'Guinea'],
        ['iso' => 'GW', 'name' => 'Guinea-Bissau'],
        ['iso' => 'GY', 'name' => 'Guyana'],
        ['iso' => 'HT', 'name' => 'Haiti'],
        ['iso' => 'HN', 'name' => 'Honduras'],
        ['iso' => 'HK', 'name' => 'Hong Kong'],
        ['iso' => 'HU', 'name' => 'Hungary'],
        ['iso' => 'IS', 'name' => 'Iceland'],
        ['iso' => 'IN', 'name' => 'India'],
        ['iso' => 'ID', 'name' => 'Indonesia'],
        ['iso' => 'IR', 'name' => 'Iran'],
        ['iso' => 'IQ', 'name' => 'Iraq'],
        ['iso' => 'IE', 'name' => 'Ireland'],
        ['iso' => 'IL', 'name' => 'Israel'],
        ['iso' => 'IT', 'name' => 'Italy'],
        ['iso' => 'CI', 'name' => 'Ivory Coast'],
        ['iso' => 'JM', 'name' => 'Jamaica'],
        ['iso' => 'JP', 'name' => 'Japan'],
        ['iso' => 'JO', 'name' => 'Jordan'],
        ['iso' => 'KZ', 'name' => 'Kazakhstan'],
        ['iso' => 'KE', 'name' => 'Kenya'],
        ['iso' => 'KI', 'name' => 'Kiribati'],
        ['iso' => 'KR', 'name' => 'Korea, South'],
        ['iso' => 'XK', 'name' => 'Kosova'],
        ['iso' => 'KW', 'name' => 'Kuwait'],
        ['iso' => 'KG', 'name' => 'Kyrgyzstan'],
        ['iso' => 'LA', 'name' => 'Laos'],
        ['iso' => 'LV', 'name' => 'Latvia'],
        ['iso' => 'LR', 'name' => 'Liberia'],
        ['iso' => 'LY', 'name' => 'Libya'],
        ['iso' => 'LB', 'name' => 'Lebanon'],
        ['iso' => 'LS', 'name' => 'Lesotho'],
        ['iso' => 'LI', 'name' => 'Liechtenstein'],
        ['iso' => 'LT', 'name' => 'Lithuania'],
        ['iso' => 'LU', 'name' => 'Luxembourg'],
        ['iso' => 'MO', 'name' => 'Macau'],
        ['iso' => 'MK', 'name' => 'Macedonia, Republic of'],
        ['iso' => 'MG', 'name' => 'Madagascar'],
        ['iso' => 'MW', 'name' => 'Malawi'],
        ['iso' => 'MY', 'name' => 'Malaysia'],
        ['iso' => 'MV', 'name' => 'Maldives'],
        ['iso' => 'ML', 'name' => 'Mali'],
        ['iso' => 'MT', 'name' => 'Malta'],
        ['iso' => 'MH', 'name' => 'Marshall Islands'],
        ['iso' => 'MQ', 'name' => 'Martinique'],
        ['iso' => 'MR', 'name' => 'Mauritania'],
        ['iso' => 'MU', 'name' => 'Mauritius'],
        ['iso' => 'YT', 'name' => 'Mayotte'],
        ['iso' => 'MX', 'name' => 'Mexico'],
        ['iso' => 'FM', 'name' => 'Micronesia'],
        ['iso' => 'MD', 'name' => 'Moldova'],
        ['iso' => 'MC', 'name' => 'Monaco'],
        ['iso' => 'MN', 'name' => 'Mongolia'],
        ['iso' => 'ME', 'name' => 'Montenegro'],
        ['iso' => 'MS', 'name' => 'Montserrat'],
        ['iso' => 'MA', 'name' => 'Morocco'],
        ['iso' => 'MZ', 'name' => 'Mozambique'],
        ['iso' => 'NA', 'name' => 'Namibia'],
        ['iso' => 'NR', 'name' => 'Nauru'],
        ['iso' => 'NP', 'name' => 'Nepal'],
        ['iso' => 'NL', 'name' => 'Netherlands'],
        ['iso' => 'AN', 'name' => 'Netherlands Antilles'],
        ['iso' => 'NC', 'name' => 'New Caledonia'],
        ['iso' => 'NZ', 'name' => 'New Zealand'],
        ['iso' => 'NI', 'name' => 'Nicaragua'],
        ['iso' => 'NE', 'name' => 'Niger'],
        ['iso' => 'NG', 'name' => 'Nigeria'],
        ['iso' => 'NU', 'name' => 'Niue'],
        ['iso' => 'NF', 'name' => 'Norfolk Island'],
        ['iso' => 'NO', 'name' => 'Norway'],
        ['iso' => 'OM', 'name' => 'Oman'],
        ['iso' => 'PK', 'name' => 'Pakistan'],
        ['iso' => 'PS', 'name' => 'Palestinian Territory'],
        ['iso' => 'PA', 'name' => 'Panama'],
        ['iso' => 'PG', 'name' => 'Papua New Guinea'],
        ['iso' => 'PY', 'name' => 'Paraguay'],
        ['iso' => 'PE', 'name' => 'Peru'],
        ['iso' => 'PH', 'name' => 'Philippines'],
        ['iso' => 'PN', 'name' => 'Pitcairn Island'],
        ['iso' => 'PL', 'name' => 'Poland'],
        ['iso' => 'PR', 'name' => 'Puerto Rico'],
        ['iso' => 'PT', 'name' => 'Portugal'],
        ['iso' => 'QA', 'name' => 'Qatar'],
        ['iso' => 'RE', 'name' => 'Réunion'],
        ['iso' => 'RO', 'name' => 'Romania'],
        ['iso' => 'RU', 'name' => 'Russia'],
        ['iso' => 'RW', 'name' => 'Rwanda'],
        ['iso' => 'SH', 'name' => 'Saint Helena'],
        ['iso' => 'KN', 'name' => 'Saint Kitts and Nevis'],
        ['iso' => 'LC', 'name' => 'Saint Lucia'],
        ['iso' => 'MF', 'name' => 'Saint Martin'],
        ['iso' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
        ['iso' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
        ['iso' => 'WS', 'name' => 'Samoa'],
        ['iso' => 'SM', 'name' => 'San Marino'],
        ['iso' => 'ST', 'name' => 'São Tome and Principe'],
        ['iso' => 'SA', 'name' => 'Saudi Arabia'],
        ['iso' => 'SN', 'name' => 'Senegal'],
        ['iso' => 'RS', 'name' => 'Serbia'],
        ['iso' => 'CS', 'name' => 'Serbia and Montenegro'],
        ['iso' => 'SC', 'name' => 'Seychelles'],
        ['iso' => 'SL', 'name' => 'Sierra Leon'],
        ['iso' => 'SG', 'name' => 'Singapore'],
        ['iso' => 'SK', 'name' => 'Slovakia'],
        ['iso' => 'SI', 'name' => 'Slovenia'],
        ['iso' => 'SB', 'name' => 'Solomon Islands'],
        ['iso' => 'SO', 'name' => 'Somalia'],
        ['iso' => 'ZA', 'name' => 'South Africa'],
        ['iso' => 'SS', 'name' => 'South Sudan'],
        ['iso' => 'ES', 'name' => 'Spain'],
        ['iso' => 'LK', 'name' => 'Sri Lanka'],
        ['iso' => 'SD', 'name' => 'Sudan'],
        ['iso' => 'SR', 'name' => 'Suriname'],
        ['iso' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
        ['iso' => 'SZ', 'name' => 'Swaziland'],
        ['iso' => 'SE', 'name' => 'Sweden'],
        ['iso' => 'CH', 'name' => 'Switzerland'],
        ['iso' => 'SY', 'name' => 'Syria'],
        ['iso' => 'TW', 'name' => 'Taiwan'],
        ['iso' => 'TJ', 'name' => 'Tajikistan'],
        ['iso' => 'TZ', 'name' => 'Tanzania'],
        ['iso' => 'TH', 'name' => 'Thailand'],
        ['iso' => 'TG', 'name' => 'Togo'],
        ['iso' => 'TK', 'name' => 'Tokelau'],
        ['iso' => 'TO', 'name' => 'Tonga'],
        ['iso' => 'TT', 'name' => 'Trinidad and Tobago'],
        ['iso' => 'TN', 'name' => 'Tunisia'],
        ['iso' => 'TR', 'name' => 'Turkey'],
        ['iso' => 'TM', 'name' => 'Turkmenistan'],
        ['iso' => 'TC', 'name' => 'Turks and Caicos Islands'],
        ['iso' => 'TV', 'name' => 'Tuvalu'],
        ['iso' => 'UG', 'name' => 'Uganda'],
        ['iso' => 'UA', 'name' => 'Ukraine'],
        ['iso' => 'AE', 'name' => 'United Arab Emirates'],
        ['iso' => 'GB', 'name' => 'United Kingdom'],
        ['iso' => 'UM', 'name' => 'United States Minor Outlying Islands'],
        ['iso' => 'UY', 'name' => 'Uruguay'],
        ['iso' => 'UZ', 'name' => 'Uzbekistan'],
        ['iso' => 'VU', 'name' => 'Vanuatu'],
        ['iso' => 'VA', 'name' => 'Vatican City'],
        ['iso' => 'VE', 'name' => 'Venezuela'],
        ['iso' => 'VN', 'name' => 'Vietnam'],
        ['iso' => 'WF', 'name' => 'Wallis and Futuna'],
        ['iso' => 'EH', 'name' => 'Western Sahara'],
        ['iso' => 'YE', 'name' => 'Yemen'],
        ['iso' => 'ZM', 'name' => 'Zambia'],
        ['iso' => 'ZW', 'name' => 'Zimbabwe']
    ];

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('iso', 2);
            $table->string('name', 75);
            $table->timestamps();
        });
        Country::insert($this->countries);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
