const defaultTheme = require('tailwindcss/defaultTheme')
const tinycolor = require('tinycolor2')

module.exports = {
  theme: {
    darkSelector: '.dark-mode',
    extend: {
      screens: {
        '2xl': '1440px',
        dark: {raw: '(prefers-color-scheme: dark)'},
        light: {raw: '(prefers-color-scheme: light)'},
      },
      colors: {
        teal: {
          100: "#d5f0e0",
          200: "#abe1c1",
          300: "#81d3a2",
          400: "#57c483",
          500: "#2db564",
          600: "#249150",
          700: "#1b6d3c",
          800: "#124828",
          900: "#092414",
        },
        'booster-blue': '#003E7E',
        'booster-red': '#B3282D',
        'primary-25': tinycolor('#2f855a').setAlpha(0.25).toRgbString(),
        'primary-50': tinycolor('#2f855a').setAlpha(0.5).toRgbString(),
        'primary-75': tinycolor('#2f855a').setAlpha(0.75).toRgbString(),
        primary: {
          100: '#EAF8F0',
          200: '#CBEDD8',
          300: '#ABE1C1',
          400: '#6CCB93',
          500: '#2DB564',
          600: '#29A35A',
          700: '#1B6D3C',
          800: '#14512D',
          900: '#0E361E',
        },
        'secondary-25': tinycolor('#2b6cb0').setAlpha(0.25).toRgbString(),
        'secondary-50': tinycolor('#2b6cb0').setAlpha(0.5).toRgbString(),
        'secondary-75': tinycolor('#2b6cb0').setAlpha(0.75).toRgbString(),
        secondary: {
          100: '#EAF3FC',
          200: '#CBE1F7',
          300: '#ABCFF2',
          400: '#6DAAE8',
          500: '#2E86DE',
          600: '#2979C8',
          700: '#1C5085',
          800: '#153C64',
          900: '#0E2843',
        },
        'tertiary-25': tinycolor('#ed8936').setAlpha(0.25).toRgbString(),
        'tertiary-50': tinycolor('#ed8936').setAlpha(0.5).toRgbString(),
        'tertiary-75': tinycolor('#ed8936').setAlpha(0.75).toRgbString(),
        tertiary: {
          100: '#FFF6EB',
          200: '#FEE9CD',
          300: '#FDDBAF',
          400: '#FCC174',
          500: '#FAA638',
          600: '#E19532',
          700: '#966422',
          800: '#714B19',
          900: '#4B3211',
        },
        danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        success: 'var(--color-success)',
        info: 'var(--color-info)',
        email: 'var(--color-emailer)',
        emailer: 'var(--color-emailer)',
        sms: 'var(--color-sms)',
        copy: 'var(--color-copy)',
        brand: '#1B2A60',
        facebook: '#3b5998',
        twitter: '#1da1f2',
        linkedin: '#0077b5',
      },
      fontFamily: {
        sans: ['Source Sans Pro', 'Inter var', ...defaultTheme.fontFamily.sans],
        mono: ['Cousine', 'Input Mono', ...defaultTheme.fontFamily.mono],
      },
      fontSize: {
        '2xs': '0.65rem',
      },
      spacing: {
        44: '11rem',
        72: '18rem',
        84: '21rem',
        80: '20rem',
        96: '24rem',
      },
      borderWidth: {
        3: '3px',
        5: '5px',
      },
    },
    aspectRatio: {
      square: [1, 1],
      '16/9': [16, 9],
      '4/3': [4, 3],
      '21/9': [21, 9],
    },
    spinner: theme => ({
      default: {
        color: '#DAE1E7',
        size: '1rem',
        border: '2px',
        speed: '500ms',
      },
      md: {
        color: theme('colors.red.500', 'red'),
        size: '2em',
        border: '2px',
        speed: '500ms',
      },
    }),
  },
  variants: {
    backgroundColor: ['responsive', 'group-hover', 'hover', 'focus', 'active'],
    borderColor: [
      'focus-within',
      'responsive',
      'group-hover',
      'hover',
      'focus',
    ],
    borderStyle: ['responsive', 'hover'],
    display: ['responsive', 'group-hover'],
    textColor: [
      'responsive',
      'group-hover',
      'hover',
      'focus-within',
      'focus',
      'active',
    ],
    zIndex: ['responsive', 'focus-within', 'focus'],
  },
  plugins: [
    require('@tailwindcss/ui'),
    require('tailwindcss-aspect-ratio'),
    require('tailwindcss-elevation')(['responsive']),
    require('tailwindcss-spinner')(),
    require('tailwindcss-scrims')({
      directions: {
        t: 'to bottom',
        b: 'to top',
        r: 'to left',
        l: 'to right',
      },
      distances: {
        '1/4': '25%',
        '1/3': '33.33333%',
        '1/2': '50%',
        '2/3': '66.66666%',
        '3/4': '75%',
      },
      colors: {
        default: ['rgba(0, 0, 0, 0.4)', 'rgba(0, 0, 0, 0)'],
      },
      variants: ['responsive', 'hover'],
    }),
  ],
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.vue',
      'components/**/*.js',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
    ],
    options: {
      whitelist: ['bg-red-500', 'px-4'],
    },
  },
}
